# Generated by Django 4.0.6 on 2022-07-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Photo3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image3', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Photo4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image4', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Photo5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image5', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Photo6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image6', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='photo1',
            name='image1',
            field=models.ImageField(upload_to=''),
        ),
    ]
