# Generated by Django 4.0.6 on 2022-07-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_photo2_photo3_photo4_photo5_photo6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo1',
            name='image1',
            field=models.ImageField(upload_to='1/'),
        ),
        migrations.AlterField(
            model_name='photo2',
            name='image2',
            field=models.ImageField(upload_to='2/'),
        ),
        migrations.AlterField(
            model_name='photo3',
            name='image3',
            field=models.ImageField(upload_to='3/'),
        ),
        migrations.AlterField(
            model_name='photo4',
            name='image4',
            field=models.ImageField(upload_to='4/'),
        ),
        migrations.AlterField(
            model_name='photo5',
            name='image5',
            field=models.ImageField(upload_to='5/'),
        ),
        migrations.AlterField(
            model_name='photo6',
            name='image6',
            field=models.ImageField(upload_to='6/'),
        ),
    ]
