# Generated by Django 4.0.6 on 2022-07-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_photo1_image1_alter_photo2_image2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo2',
        ),
        migrations.DeleteModel(
            name='Photo3',
        ),
        migrations.DeleteModel(
            name='Photo4',
        ),
        migrations.DeleteModel(
            name='Photo5',
        ),
        migrations.DeleteModel(
            name='Photo6',
        ),
    ]
