# Generated by Django 4.0.6 on 2022-07-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_photo2_delete_photo3_delete_photo4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo1',
            name='image1',
            field=models.ImageField(upload_to='image1/'),
        ),
    ]
