# Generated by Django 4.0.6 on 2022-07-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_photo1_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo1',
            name='image1',
            field=models.ImageField(upload_to='blog/%Y/%m/%d'),
        ),
    ]
