# Generated by Django 4.0.6 on 2022-07-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_photo1_image1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo1',
        ),
    ]
